version: 2.1

jobs:
  terraform_apply:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: terraform init
      - run:
          name: Terraform Plan
          command: terraform plan
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve
      - persist_to_workspace:
          root: .
          paths:
            - terraform.tfstate

workflows:
  version: 2
  apply:
    jobs:
      - terraform_apply
