version: 2.1

jobs:
  terraform_apply:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout

      - run:
          name: Terraform Init
          command: terraform init

      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve

workflows:
  version: 2
  apply:
    jobs:
      - terraform_apply
